config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => "/sidekiq"

  resources :repos, only: [:index] do
    collection do
      post :action
    end
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "repos#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/repo.rb
class Repo < ApplicationRecord
  has_one_attached :indexed_repo_file

  HUMANIZED_ATTRIBUTES = {
    :email => "E-mail address",
    :url => "Github Repository URL"
  }

  validates :url, format: {
    with: /\Ahttps:\/\/github\.com\/[a-zA-Z0-9._-]+\/[a-zA-Z0-9._-]+\z/,
    message: 'must be valid and present.'
  }
  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP, message: 'address string must be present and valid.' }

  def self.human_attribute_name(attr, options = {})
    HUMANIZED_ATTRIBUTES[attr.to_sym] || super
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/repos_controller.rb
class ReposController < ApplicationController

  def index
  end

  def action
    @repo = Repo.new(url: params[:repo], email: params[:email])
    render and return unless @repo.valid?

    @repo.save!
    ProcessRepoJob.perform_later(@repo)
  end

  def async_load_repo
    @clone = Clone.new(params[:repo])
    @file = @clone.file_from_repo
    send_data @file, filename: 'repo.md'


  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/heroicon_helper.rb
# frozen_string_literal: true

module HeroiconHelper
  include Heroicon::Engine.helpers
end

app/helpers/repos_helper.rb
module ReposHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CodebaseChat</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/devicons/devicon@v2.15.1/devicon.min.css">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
      <%= yield %>
  </body>
</html>

app/views/repos/action.html.erb
<%= turbo_frame_tag 'result' do %>
  <% if @repo.valid? %>
    <div class="flex items-center gap-2">
      <%= heroicon 'check-circle', variant: :outline, options: { class: 'w-8 h-8'} %>
      <span class="">
        <div class="font-semibold">Success!</div>
        <div class="text-slate-400 text-xs">
        Your indexed repo is being processed and will be emailed to you shortly.
        </div>
      </span>
    </div>
  <% else %>
    <div class="flex items-center gap-2">
      <%= heroicon 'x-circle', variant: :outline, options: { class: 'w-8 h-8'} %>
      <span class="">
        <div class="font-semibold">Invalid submission.</div>
        <div class="text-slate-400 text-xs">
          <%= @repo.errors.full_messages.first %>
        </div>
      </span>
    </div>
  <% end %>
<% end %>

app/views/repos/index.html.erb
<div class="w-full min-h-screen bg-slate-800 text-slate-200">
  <div class="w-full p-2 flex items-center justify-center bg-slate-700 gap-1 border-b border-slate-500">
    Made in <span class="font-bold">London</span> by
    <div class="h-5">
      <%= link_to 'http://context.ai/?utm_source=codebasechat&utm_medium=site' do %>
        <%= image_tag 'logo_white.png', class: 'h-full' %>
      <% end %>
    </div>
  </div>
  <div class="py-4 font-bold noto-serif text-lg max-w-6xl mx-auto">
  </div>
  <div class="p-16">
    <div class="flex items-center flex-col gap-16 justify-center">
      <div class="grid grid-cols-12 max-w-7xl gap-16 justify-center items-center">
        <div class="flex flex-col gap-8 shrink xl:col-span-5 col-span-12">
          <div class="text-6xl max-w-xl noto-serif">
            <div class="mb-2 font-semibold">
              Create a GPT chatbot for any GitHub repo in
            </div>
            <div class="relative inline-block group">
              <div class="relative z-10 font-semibold text-slate-800 p-2">30 seconds</div>
              <div class="top-0 absolute bg-white w-full h-full -rotate-1 group-hover:rotate-2 duration-200 transition-all"></div>
            </div>

          </div>
          <div class="flex flex-col rounded gap-4">
            <div class="font-semibold text-slate-400">
              Every major programming language supported:
            </div>

            <div class="text-slate-300 text-4xl gap-8 flex items-center">
              <i class="highlight devicon-c-plain"></i>
              <i class="highlight devicon-python-plain"></i>
              <i class="highlight devicon-javascript-plain"></i>
              <i class="highlight devicon-ruby-plain"></i>
              <i class="highlight devicon-go-plain"></i>
              <i class="highlight devicon-java-plain"></i>
              <div class="plus text-sm">...and more</div>
            </div>
          </div>
        </div>

        <div class="steps max-w-4xl col-span-12 xl:col-span-7 w-full flex flex-col gap-8 p-8 rounded bg-slate-700 shadow border border-slate-600">
          <div class="first flex gap-8 items-baseline">
            <div class="rounded-full bg-slate-100 w-10 h-10 flex text-slate-600 items-center justify-center font-semibold text-lg shrink-0">1</div>
            <div class="col-span-11 flex flex-col gap-4">
              <div class="text-2xl">Enter your GitHub repository URL:</div>
              <div class="text-sm prose text-slate-300">We will crawl your repo and email you an index file you can upload directly to your GPT.</div>
              <%= turbo_frame_tag 'form' do %>
                <%= form_with url: action_repos_path, data: { 'turbo-frame': 'result' } do |form| %>
                  <div class="flex w-full gap-4">
                    <div class="grow">
                      <div class="font-semibold mb-1">GitHub Repo Link</div>
                      <%= form.text_field :repo, placeholder: 'https://github.com/tldraw/tldraw', class: 'rounded border-slate-500 bg-slate-600 text-slate-100 placeholder:text-slate-400 w-full' %>
                    </div>

                    <div>
                      <div class="font-semibold mb-1">Email</div>
                      <%= form.text_field :email, placeholder: 'alex@example.com', class: 'rounded border-slate-500 bg-slate-600 text-slate-100 placeholder:text-slate-400' %>
                    </div>


                  </div>
                  <div class="flex items-center gap-8">
                    <%= form.submit "Submit", class: 'border-slate-500 border p-2 rounded my-4 cursor-pointer' %>

                    <%= turbo_frame_tag 'result', class: 'grow' %>
                  </div>
                <% end %>
              <% end %>
            </div>
          </div>

          <div class="first flex gap-8  items-baseline">
            <div class="rounded-full bg-slate-100 w-10 h-10 flex text-slate-600 items-center justify-center font-semibold text-lg shrink-0">2</div>
            <div class="col-span-11 flex flex-col gap-4">
              <div class="text-2xl">Upload your GPT codebase file:</div>

              <div class="text-sm prose text-slate-300">You will receive an email with a link to a file <span class="font-mono p-1 bg-slate-500  rounded ">repo.md</span>. You can then <a class="text-slate-300" href="https://chat.openai.com/gpts/editor">upload that file to OpenAI</a> to create your custom codebase GPT.</div>

            </div>
          </div>
        </div>

      </div>
    </div>

    <div class="faqs flex justify-center my-16">
      <div class="max-w-4xl grow flex flex-col gap-4 border-t border-slate-600 py-8 items-center text-left">
        <div class="flex flex-col gap-8">
          <div class="text-2xl font-bold">Frequently Asked Questions</div>

          <div class="question">
            <div class="text-lg font-semibold text-xl">
              How does this work?
            </div>
            <div class="prose text-slate-400">
              CodebaseChat clones and crawls your repo to create a file that you can upload to OpenAI's new GPTs or Assistants. OpenAI GPTs and Assistants currently have a 20 file limit when using the retrieval features, so for now you need to upload a single indexed file to allow them to operate over large amounts of data.
            </div>
          </div>

          <div class="question">
            <div class="text-lg font-semibold text-xl">
              How should I prompt my GPT or assistant to make full use of the file?
            </div>
            <div class="prose text-slate-400">
              We recommend using a prompt that tells the GPT about the contents of your codebase.

              For example, at Context.ai we use the following prompt in our GPT:

            </div>
            <div class="font-mono p-2 bg-slate-700 rounded text-slate-400 max-w-prose">
              You are a code assistant for the Git repo of Context AI. Context AI is a startup that is building product analytics software for natural language interfaces where users are interacting with LLMs. The product ingests transcripts of its customers, then provides analytics about those interactions, such as topics, sentiment analysis, languages spoken and more. The contents of the codebase are stored in repo.md, with the contents of each file under a new Markdown header.
            </div>
          </div>

          <div class="question">
            <div class="text-lg font-semibold text-xl">
              Can I modify the code or suggest changes to CodebaseChat?
            </div>
            <div class="prose text-slate-400">
              Yes! CodebaseChat is open-source and we welcome contributions. You can find the repo <a class="text-slate-300" href="https://github.com/contextco/codebasechat">here</a>.
            </div>
          </div>

          <div class="question">
            <div class="text-lg font-semibold text-xl">
              I don't have ChatGPT Plus, can I still use this?
            </div>
            <div class="prose text-slate-400">
              Yes, you can instead upload the repo file in the <a class="text-slate-300" href='https://platform.openai.com/playground'>OpenAI Assistants Playground</a> and ask questions of your repo with the GPT API free tier.
            </div>
          </div>

          <div class="question">
            <div class="text-lg font-semibold text-xl">
              Do you support private repos?
            </div>
            <div class="prose text-slate-400">
              We don't yet support private repos. Contact us <a class="text-slate-300" href="https://forms.gle/PZrxJLCAR1Evgshn6">here</a> if you'd like to be notified when we launch this.
            </div>
          </div>

          <div class="question">
            <div class="text-lg font-semibold text-xl">
              I have another feature request, how can I contact you?
            </div>
            <div class="prose text-slate-400">
              You can add your feature requests <a class="text-slate-300" href="https://forms.gle/PZrxJLCAR1Evgshn6">here</a>.
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>


</div>